name: Build and Release APK

on:
  push:
    branches:
      - main

jobs:
  build:
    permissions: write-all
    environment: dev
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Set up Android SDK
      - name: Set up Android SDK
        run: |
          echo "Installing Android SDK"
          sudo apt-get update
          sudo apt-get install -y openjdk-17-jdk
          sudo mkdir /opt/android-sdk
          sudo chown -R $USER:$USER /opt/
          wget "https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip" -O latest.zip
          unzip latest.zip
          mv cmdline-tools /opt/
          export PATH="/opt/cmdline-tools/bin:$PATH"
          yes | sdkmanager --licenses --sdk_root=/opt/android-sdk
          sdkmanager --sdk_root=/opt/android-sdk "platform-tools" "build-tools;30.0.3" "platforms;android-30"
          sed -i 's/org.gradle.java.home.*//' gradle.properties

      # Build the APK
      - name: Build APK
        run: ./gradlew build

      # Upload the APK as a GitHub Release
      - name: Create GitHub Release
        id: release
        run: |
          TAG_NAME="v$(date +'%Y%m%d%H%M%S')"
          gh release create $TAG_NAME app/build/outputs/apk/debug/app-debug.apk \
            --title "Release $TAG_NAME" \
            --notes "Release version $TAG_NAME"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
