name: Release

on:
  workflow_dispatch:  # Allows manual trigger only

jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: |
        printf "$KEYSTORE" | base64 -d > keystore.jks
        sed -i '${/^}$/d}' build.gradle.kts
        cat misc/release-config.txt >> build.gradle.kts
        echo '}' >> build.gradle.kts
        ./gradlew assembleRelease
        shred keystore.jks
      env:
        KEYSTORE: ${{ secrets.KEYSTORE }}
        KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
        KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
        KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        KEYSTORE_PATH: "keystore.jks"

    - name: Create GitHub Release
      id: release
      run: |
        TAG="v$(date +'%Y%m%d%H%M%S')"
        gh release create "$TAG" build/outputs/apk/release/*.apk \
          --title "Release $TAG" \
          --notes "Release version $TAG"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
